name: Build and Test Compiler & VM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Set a max job duration of 10 minutes

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # or 7.0.x depending on your compiler

      - name: Restore and build compiler
        run: |
          cd Compiler/Compiler
          dotnet restore
          dotnet build --configuration Release

      - name: Build Rust VM
        run: |
          cd vm
          cargo build --verbose

      - name: Run tests
        run: |
          mkdir tests/out
          cd vm
          cargo test -- --test-threads=1
